CREATE TABLE `forms` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updatedAt` text DEFAULT (CURRENT_TIMESTAMP),
	`version` integer DEFAULT 1 NOT NULL,
	`pinId` text,
	`villageId` text,
	`name` text,
	`gender` text,
	`age` integer,
	`village` text,
	`canAttendHealthScreening` integer,
	`longTermConditions` text,
	`otherLongTermConditions` text,
	`managementMethods` text,
	`otherManagementMethods` text,
	`conditionDifficultyReasons` text,
	`otherConditionDifficultyReasons` text,
	`selfCareActions` text,
	`otherSelfCareActions` text,
	`knowWhereToFindDoctor` text,
	`otherKnowWhereToFindDoctor` text,
	`transportToClinic` text,
	`otherTransportToClinic` text,
	`medicinePurchaseLocations` text,
	`otherMedicinePurchaseLocations` text,
	`povertyCardSchemeAwareness` text,
	`otherPovertyCardSchemeAwareness` text,
	`povertyCardNonUseReasons` text,
	`toothBrushingFrequency` text,
	`otherToothBrushingFrequency` text,
	`toothbrushAndToothpasteSource` text,
	`noToothbrushOrToothpasteReasons` text,
	`otherNoToothbrushOrToothpasteReasons` text,
	`diarrhoeaDefinition` text,
	`otherDiarrhoeaDefinition` text,
	`diarrhoeaActions` text,
	`otherDiarrhoeaActions` text,
	`commonColdSymptoms` text,
	`otherCommonColdSymptoms` text,
	`commonColdActions` text,
	`otherCommonColdActions` text,
	`mskInjuryDefinition` text,
	`otherMskInjuryDefinition` text,
	`mskInjuryActions` text,
	`otherMskInjuryActions` text,
	`hypertensionDefinition` text,
	`otherHypertensionDefinition` text,
	`hypertensionActions` text,
	`otherHypertensionActions` text,
	`healthyFoodFrequency` text,
	`otherHealthyFoodFrequency` text,
	`unhealthyFoodReasons` text,
	`otherUnhealthyFoodReasons` text,
	`highCholesterolDefinition` text,
	`otherHighCholesterolDefinition` text,
	`highCholesterolActions` text,
	`otherHighCholesterolActions` text,
	`diabetesDefinition` text,
	`otherDiabetesDefinition` text,
	`diabetesActions` text,
	`otherDiabetesActions` text,
	`otherLearningAreas` text,
	`waterSources` text,
	`otherWaterSources` text,
	`unsafeWaterTypes` text,
	`otherUnsafeWaterTypes` text,
	`waterFilterAwareness` text,
	`otherWaterFilterAwareness` text,
	`waterFilterNonUseReasons` text,
	`otherWaterFilterNonUseReasons` text,
	`handwashingAfterToilet` text,
	`otherHandwashingAfterToilet` text,
	`status` text,
	FOREIGN KEY (`pinId`) REFERENCES `pins`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `pins` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updatedAt` text DEFAULT (CURRENT_TIMESTAMP),
	`version` integer DEFAULT 1 NOT NULL,
	`lat` real,
	`lng` real,
	`type` text,
	`name` text,
	`address` text,
	`cityVillage` text,
	`description` text,
	`images` text,
	`status` text
);
--> statement-breakpoint
CREATE TABLE `sync_queue` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`operation` text NOT NULL,
	`entityType` text NOT NULL,
	`entityId` text NOT NULL,
	`idempotencyKey` text NOT NULL,
	`payload` text NOT NULL,
	`status` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`maxAttempts` integer DEFAULT 3 NOT NULL,
	`lastError` text,
	`lastAttemptAt` text,
	`sequenceNumber` integer,
	`dependsOn` text,
	`deviceId` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `sync_queue_idempotencyKey_unique` ON `sync_queue` (`idempotencyKey`);