PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_forms` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer,
	`version` integer DEFAULT 1 NOT NULL,
	`pinId` text NOT NULL,
	`status` text,
	`villageId` text NOT NULL,
	`name` text NOT NULL,
	`village` text NOT NULL,
	`householdNumber` text,
	`gender` text,
	`age` integer,
	`canAttendHealthScreening` integer,
	`conflictHealthcareAccess` text,
	`conflictHealthManagement` text,
	`conflictCleanWaterAccess` text,
	`conflictCostOfLiving` text,
	`longTermConditions` text,
	`otherLongTermConditions` text,
	`managementMethods` text,
	`otherManagementMethods` text,
	`conditionDifficultyReasons` text,
	`otherConditionDifficultyReasons` text,
	`selfCareActions` text,
	`otherSelfCareActions` text,
	`knowWhereToFindDoctor` text,
	`otherKnowWhereToFindDoctor` text,
	`transportToClinic` text,
	`otherTransportToClinic` text,
	`medicinePurchaseLocations` text,
	`otherMedicinePurchaseLocations` text,
	`povertyCardSchemeAwareness` text,
	`otherPovertyCardSchemeAwareness` text,
	`povertyCardNonUseReasons` text,
	`toothBrushingFrequency` text,
	`otherToothBrushingFrequency` text,
	`toothbrushAndToothpasteSource` text,
	`noToothbrushOrToothpasteReasons` text,
	`otherNoToothbrushOrToothpasteReasons` text,
	`diarrhoeaDefinition` text,
	`otherDiarrhoeaDefinition` text,
	`diarrhoeaActions` text,
	`otherDiarrhoeaActions` text,
	`commonColdSymptoms` text,
	`otherCommonColdSymptoms` text,
	`commonColdActions` text,
	`otherCommonColdActions` text,
	`mskInjuryDefinition` text,
	`otherMskInjuryDefinition` text,
	`mskInjuryActions` text,
	`otherMskInjuryActions` text,
	`hypertensionDefinition` text,
	`otherHypertensionDefinition` text,
	`hypertensionActions` text,
	`otherHypertensionActions` text,
	`healthyFoodFrequency` text,
	`otherHealthyFoodFrequency` text,
	`unhealthyFoodReasons` text,
	`otherUnhealthyFoodReasons` text,
	`highCholesterolDefinition` text,
	`otherHighCholesterolDefinition` text,
	`highCholesterolActions` text,
	`otherHighCholesterolActions` text,
	`diabetesDefinition` text,
	`otherDiabetesDefinition` text,
	`diabetesActions` text,
	`otherDiabetesActions` text,
	`otherLearningAreas` text,
	`waterSources` text,
	`otherWaterSources` text,
	`unsafeWaterTypes` text,
	`otherUnsafeWaterTypes` text,
	`waterHealthConsequences` text,
	`waterSocioeconomicConsequences` text,
	`waterFilterAwareness` text,
	`otherWaterFilterAwareness` text,
	`waterFilterExperience` text,
	`waterFilterNonUseReasons` text,
	`otherWaterFilterNonUseReasons` text,
	`handwashingAfterToilet` text,
	`otherHandwashingAfterToilet` text,
	`handwashingBeforeMeals` text,
	`handwashingBeforeMealsReason` text,
	`pressingHealthNeed` text,
	FOREIGN KEY (`pinId`) REFERENCES `pins`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_forms`("id", "createdAt", "updatedAt", "version", "pinId", "status", "villageId", "name", "village", "householdNumber", "gender", "age", "canAttendHealthScreening", "conflictHealthcareAccess", "conflictHealthManagement", "conflictCleanWaterAccess", "conflictCostOfLiving", "longTermConditions", "otherLongTermConditions", "managementMethods", "otherManagementMethods", "conditionDifficultyReasons", "otherConditionDifficultyReasons", "selfCareActions", "otherSelfCareActions", "knowWhereToFindDoctor", "otherKnowWhereToFindDoctor", "transportToClinic", "otherTransportToClinic", "medicinePurchaseLocations", "otherMedicinePurchaseLocations", "povertyCardSchemeAwareness", "otherPovertyCardSchemeAwareness", "povertyCardNonUseReasons", "toothBrushingFrequency", "otherToothBrushingFrequency", "toothbrushAndToothpasteSource", "noToothbrushOrToothpasteReasons", "otherNoToothbrushOrToothpasteReasons", "diarrhoeaDefinition", "otherDiarrhoeaDefinition", "diarrhoeaActions", "otherDiarrhoeaActions", "commonColdSymptoms", "otherCommonColdSymptoms", "commonColdActions", "otherCommonColdActions", "mskInjuryDefinition", "otherMskInjuryDefinition", "mskInjuryActions", "otherMskInjuryActions", "hypertensionDefinition", "otherHypertensionDefinition", "hypertensionActions", "otherHypertensionActions", "healthyFoodFrequency", "otherHealthyFoodFrequency", "unhealthyFoodReasons", "otherUnhealthyFoodReasons", "highCholesterolDefinition", "otherHighCholesterolDefinition", "highCholesterolActions", "otherHighCholesterolActions", "diabetesDefinition", "otherDiabetesDefinition", "diabetesActions", "otherDiabetesActions", "otherLearningAreas", "waterSources", "otherWaterSources", "unsafeWaterTypes", "otherUnsafeWaterTypes", "waterHealthConsequences", "waterSocioeconomicConsequences", "waterFilterAwareness", "otherWaterFilterAwareness", "waterFilterExperience", "waterFilterNonUseReasons", "otherWaterFilterNonUseReasons", "handwashingAfterToilet", "otherHandwashingAfterToilet", "handwashingBeforeMeals", "handwashingBeforeMealsReason", "pressingHealthNeed") SELECT "id", "createdAt", "updatedAt", "version", "pinId", "status", "villageId", "name", "village", "householdNumber", "gender", "age", "canAttendHealthScreening", "conflictHealthcareAccess", "conflictHealthManagement", "conflictCleanWaterAccess", "conflictCostOfLiving", "longTermConditions", "otherLongTermConditions", "managementMethods", "otherManagementMethods", "conditionDifficultyReasons", "otherConditionDifficultyReasons", "selfCareActions", "otherSelfCareActions", "knowWhereToFindDoctor", "otherKnowWhereToFindDoctor", "transportToClinic", "otherTransportToClinic", "medicinePurchaseLocations", "otherMedicinePurchaseLocations", "povertyCardSchemeAwareness", "otherPovertyCardSchemeAwareness", "povertyCardNonUseReasons", "toothBrushingFrequency", "otherToothBrushingFrequency", "toothbrushAndToothpasteSource", "noToothbrushOrToothpasteReasons", "otherNoToothbrushOrToothpasteReasons", "diarrhoeaDefinition", "otherDiarrhoeaDefinition", "diarrhoeaActions", "otherDiarrhoeaActions", "commonColdSymptoms", "otherCommonColdSymptoms", "commonColdActions", "otherCommonColdActions", "mskInjuryDefinition", "otherMskInjuryDefinition", "mskInjuryActions", "otherMskInjuryActions", "hypertensionDefinition", "otherHypertensionDefinition", "hypertensionActions", "otherHypertensionActions", "healthyFoodFrequency", "otherHealthyFoodFrequency", "unhealthyFoodReasons", "otherUnhealthyFoodReasons", "highCholesterolDefinition", "otherHighCholesterolDefinition", "highCholesterolActions", "otherHighCholesterolActions", "diabetesDefinition", "otherDiabetesDefinition", "diabetesActions", "otherDiabetesActions", "otherLearningAreas", "waterSources", "otherWaterSources", "unsafeWaterTypes", "otherUnsafeWaterTypes", "waterHealthConsequences", "waterSocioeconomicConsequences", "waterFilterAwareness", "otherWaterFilterAwareness", "waterFilterExperience", "waterFilterNonUseReasons", "otherWaterFilterNonUseReasons", "handwashingAfterToilet", "otherHandwashingAfterToilet", "handwashingBeforeMeals", "handwashingBeforeMealsReason", "pressingHealthNeed" FROM `forms`;--> statement-breakpoint
DROP TABLE `forms`;--> statement-breakpoint
ALTER TABLE `__new_forms` RENAME TO `forms`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_pins` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer,
	`version` integer DEFAULT 1 NOT NULL,
	`status` text,
	`lat` real NOT NULL,
	`lng` real NOT NULL,
	`name` text NOT NULL,
	`address` text,
	`cityVillage` text,
	`description` text,
	`type` text,
	`images` text
);
--> statement-breakpoint
INSERT INTO `__new_pins`("id", "createdAt", "updatedAt", "version", "status", "lat", "lng", "name", "address", "cityVillage", "description", "type", "images") SELECT "id", "createdAt", "updatedAt", "version", "status", "lat", "lng", "name", "address", "cityVillage", "description", "type", "images" FROM `pins`;--> statement-breakpoint
DROP TABLE `pins`;--> statement-breakpoint
ALTER TABLE `__new_pins` RENAME TO `pins`;