CREATE TABLE `forms` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text,
	`deleted_at` text,
	`pin_id` text,
	`village_id` text,
	`village` text,
	`brush_teeth` text,
	`can_attend` text,
	`cholesterol` text,
	`cholesterol_action` text,
	`cold_action` text,
	`cold_look_like` text,
	`condition_details` text,
	`diabetes` text,
	`diabetes_action` text,
	`diarrhoea` text,
	`diarrhoea_action` text,
	`eat_clean_food` text,
	`hand_after_toilet` text,
	`hand_before_meal` text,
	`have_toothbrush` text,
	`hypertension` text,
	`hypertension_action` text,
	`know_doctor` text,
	`know_water_filters` text,
	`long_term_conditions` text,
	`management_methods` text,
	`msk_action` text,
	`msk_injury` text,
	`not_using_water_filter` text,
	`other_brush_teeth` text,
	`other_buy_medicine` text,
	`other_condition` text,
	`other_learning` text,
	`other_management` text,
	`other_sick_action` text,
	`other_water_filter_reason` text,
	`other_water_source` text,
	`own_transport` text,
	`poverty_card` text,
	`unsafe_water` text,
	`water_sources` text,
	`what_do_when_sick` text,
	`where_buy_medicine` text
);
