CREATE TABLE `forms` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP,
	`deletedAt` text,
	`pinId` text,
	`villageId` text,
	`village` text,
	`brushTeeth` text,
	`canAttend` text,
	`cholesterol` text,
	`coldLookLike` text,
	`conditionDetails` text,
	`diabetes` text,
	`diarrhoea` text,
	`diarrhoeaAction` text,
	`eatCleanFood` text,
	`handAfterToilet` text,
	`handBeforeMeal` text,
	`haveToothbrush` text,
	`hypertension` text,
	`knowDoctor` text,
	`knowWaterFilters` text,
	`mskInjury` text,
	`otherBrushTeeth` text,
	`otherBuyMedicine` text,
	`otherCondition` text,
	`otherLearning` text,
	`otherManagement` text,
	`otherSickAction` text,
	`otherWaterFilterReason` text,
	`otherWaterSource` text,
	`ownTransport` text,
	`povertyCard` text,
	`whereBuyMedicine` text,
	`cholesterolAction` text,
	`coldAction` text,
	`diabetesAction` text,
	`hypertensionAction` text,
	`longTermConditions` text,
	`managementMethods` text,
	`mskAction` text,
	`notUsingWaterFilter` text,
	`unsafeWater` text,
	`waterSources` text,
	`whatDoWhenSick` text,
	`failureReason` text,
	`status` text,
	`lastSyncedAt` text,
	`lastFailedSyncAt` text
);
--> statement-breakpoint
CREATE TABLE `pins` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP,
	`deletedAt` text,
	`lat` real,
	`lng` real,
	`type` text,
	`name` text,
	`address` text,
	`cityVillage` text,
	`description` text,
	`failureReason` text,
	`status` text,
	`lastSyncedAt` text,
	`lastFailedSyncAt` text,
	`localImages` text,
	`images` text
);
--> statement-breakpoint
CREATE TABLE `sync_queue` (
	`id` text PRIMARY KEY NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`operation` text NOT NULL,
	`entityType` text NOT NULL,
	`entityId` text NOT NULL,
	`idempotencyKey` text NOT NULL,
	`payload` text NOT NULL,
	`status` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`maxAttempts` integer DEFAULT 3 NOT NULL,
	`lastError` text,
	`lastAttemptAt` text,
	`sequenceNumber` integer,
	`dependsOn` text,
	`deviceId` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `sync_queue_idempotencyKey_unique` ON `sync_queue` (`idempotencyKey`);