CREATE TABLE `forms` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` text,
	`failure_reason` text,
	`status` text,
	`last_synced_at` text,
	`last_failed_sync_at` text,
	`pin_id` text,
	`village_id` text,
	`village` text,
	`brush_teeth` text,
	`can_attend` text,
	`cholesterol` text,
	`cold_look_like` text,
	`condition_details` text,
	`diabetes` text,
	`diarrhoea` text,
	`diarrhoea_action` text,
	`eat_clean_food` text,
	`hand_after_toilet` text,
	`hand_before_meal` text,
	`have_toothbrush` text,
	`hypertension` text,
	`know_doctor` text,
	`know_water_filters` text,
	`msk_injury` text,
	`other_brush_teeth` text,
	`other_buy_medicine` text,
	`other_condition` text,
	`other_learning` text,
	`other_management` text,
	`other_sick_action` text,
	`other_water_filter_reason` text,
	`other_water_source` text,
	`own_transport` text,
	`poverty_card` text,
	`where_buy_medicine` text,
	`cholesterol_action` text,
	`cold_action` text,
	`diabetes_action` text,
	`hypertension_action` text,
	`long_term_conditions` text,
	`management_methods` text,
	`msk_action` text,
	`not_using_water_filter` text,
	`unsafe_water` text,
	`water_sources` text,
	`what_do_when_sick` text
);
--> statement-breakpoint
CREATE TABLE `pins` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	`deleted_at` text,
	`failure_reason` text,
	`status` text,
	`last_synced_at` text,
	`last_failed_sync_at` text,
	`lat` real,
	`lng` real,
	`type` text,
	`name` text,
	`address` text,
	`city/village` text,
	`description` text,
	`images` text,
	`local_images` text
);
--> statement-breakpoint
CREATE TABLE `sync_queue` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`operation` text NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`idempotency_key` text NOT NULL,
	`payload` text NOT NULL,
	`status` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`max_attempts` integer DEFAULT 3 NOT NULL,
	`last_error` text,
	`last_attempt_at` text,
	`sequence_number` integer NOT NULL,
	`depends_on` text,
	`device_id` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `sync_queue_idempotency_key_unique` ON `sync_queue` (`idempotency_key`);