CREATE TABLE "forms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	"pin_id" uuid,
	"village_id" text,
	"village" text,
	"brush_teeth" text,
	"can_attend" text,
	"cholesterol" text,
	"cold_look_like" text,
	"condition_details" text,
	"diabetes" text,
	"diarrhoea" text,
	"diarrhoea_action" text,
	"eat_clean_food" text,
	"hand_after_toilet" text,
	"hand_before_meal" text,
	"have_toothbrush" text,
	"hypertension" text,
	"know_doctor" text,
	"know_water_filters" text,
	"msk_injury" text,
	"other_brush_teeth" text,
	"other_buy_medicine" text,
	"other_condition" text,
	"other_learning" text,
	"other_management" text,
	"other_sick_action" text,
	"other_water_filter_reason" text,
	"other_water_source" text,
	"own_transport" text,
	"poverty_card" text,
	"where_buy_medicine" text,
	"cholesterol_action" text[],
	"cold_action" text[],
	"diabetes_action" text[],
	"hypertension_action" text[],
	"long_term_conditions" text[],
	"management_methods" text[],
	"msk_action" text[],
	"not_using_water_filter" text[],
	"unsafe_water" text[],
	"water_sources" text[],
	"what_do_when_sick" text[]
);
--> statement-breakpoint
CREATE TABLE "pins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone,
	"lat" double precision,
	"lng" double precision,
	"type" text,
	"name" text,
	"address" text,
	"city_village" text,
	"description" text,
	"images" text[]
);
