CREATE TABLE "forms" (
	"id" text PRIMARY KEY NOT NULL,
	"createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP,
	"deletedAt" timestamp,
	"pinId" text,
	"villageId" text,
	"village" text,
	"brushTeeth" text,
	"canAttend" text,
	"cholesterol" text,
	"coldLookLike" text,
	"conditionDetails" text,
	"diabetes" text,
	"diarrhoea" text,
	"diarrhoeaAction" text,
	"eatCleanFood" text,
	"handAfterToilet" text,
	"handBeforeMeal" text,
	"haveToothbrush" text,
	"hypertension" text,
	"knowDoctor" text,
	"knowWaterFilters" text,
	"mskInjury" text,
	"otherBrushTeeth" text,
	"otherBuyMedicine" text,
	"otherCondition" text,
	"otherLearning" text,
	"otherManagement" text,
	"otherSickAction" text,
	"otherWaterFilterReason" text,
	"otherWaterSource" text,
	"ownTransport" text,
	"povertyCard" text,
	"whereBuyMedicine" text,
	"cholesterolAction" text,
	"coldAction" text,
	"diabetesAction" text,
	"hypertensionAction" text,
	"longTermConditions" text,
	"managementMethods" text,
	"mskAction" text,
	"notUsingWaterFilter" text,
	"unsafeWater" text,
	"waterSources" text,
	"whatDoWhenSick" text
);
--> statement-breakpoint
CREATE TABLE "pins" (
	"id" text PRIMARY KEY NOT NULL,
	"createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP,
	"deletedAt" timestamp,
	"lat" double precision,
	"lng" double precision,
	"type" text,
	"name" text,
	"address" text,
	"cityVillage" text,
	"description" text,
	"images" text
);
